---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: capstoneudacity-eksctl
  region: us-west-2
  version: "1.21"

availabilityZones: ["us-west-2a", "us-west-2b", "us-west-2c"]

managedNodeGroups:
- name: nodegroup
  desiredCapacity: 3
  instanceType: t2.micro
  ssh:
    allow: true
    publicKeyName: capstone

# To enable all of the control plane logs, uncomment below:
# cloudWatch:
#  clusterLogging:
#    enableTypes: ["*"]

secretsEncryption:
  keyARN: arn:aws:kms:us-west-2:660171700894:key/cbd819d2-2262-478e-a7fc-8db3ca9d35ae

