---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: capstoneudacity-eksctl
  region: us-east-1
  version: "1.17"

availabilityZones: ["us-east-1a", "us-east-1b", "us-east-1c"]

managedNodeGroups:
- name: nodegroup
  desiredCapacity: 3
  instanceType: t2.micro
  ssh:
    allow: true
    publicKeyName: capstone

# To enable all of the control plane logs, uncomment below:
# cloudWatch:
#  clusterLogging:
#    enableTypes: ["*"]

secretsEncryption:
  keyARN: arn:aws:kms:us-west-2:660171700894:key/cbd819d2-2262-478e-a7fc-8db3ca9d35ae

